// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: favorite.sql

package sqlc

import (
	"context"
	"database/sql"
)

const addFavorite = `-- name: AddFavorite :exec
INSERT INTO favorites(
    session_id,
    user_id,
    book_id
)
VALUES ($1, $2, $3)
`

type AddFavoriteParams struct {
	SessionID sql.NullString
	UserID    sql.NullInt64
	BookID    int64
}

func (q *Queries) AddFavorite(ctx context.Context, arg AddFavoriteParams) error {
	_, err := q.db.ExecContext(ctx, addFavorite, arg.SessionID, arg.UserID, arg.BookID)
	return err
}

const getFavoritesBySession = `-- name: GetFavoritesBySession :many
SELECT
    b.id, b.title, b.author, b.price
FROM favorites f
         JOIN books b ON b.id = f.book_id
WHERE f.session_id = $1
`

func (q *Queries) GetFavoritesBySession(ctx context.Context, sessionID sql.NullString) ([]Book, error) {
	rows, err := q.db.QueryContext(ctx, getFavoritesBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Author,
			&i.Price,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFavoritesByUser = `-- name: GetFavoritesByUser :many
SELECT
    b.id, b.title, b.author, b.price
FROM favorites f
         JOIN books b ON b.id = f.book_id
WHERE f.user_id = $1
`

func (q *Queries) GetFavoritesByUser(ctx context.Context, userID sql.NullInt64) ([]Book, error) {
	rows, err := q.db.QueryContext(ctx, getFavoritesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Author,
			&i.Price,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isFavorite = `-- name: IsFavorite :one
SELECT EXISTS(
    SELECT 1
    FROM favorites
    WHERE book_id = $1
      AND (
        session_id = $2
            OR user_id = $3
        )
)
`

type IsFavoriteParams struct {
	BookID    int64
	SessionID sql.NullString
	UserID    sql.NullInt64
}

func (q *Queries) IsFavorite(ctx context.Context, arg IsFavoriteParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isFavorite, arg.BookID, arg.SessionID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const moveFavoritesToUser = `-- name: MoveFavoritesToUser :exec
UPDATE favorites
SET user_id = $1,
    session_id = NULL
WHERE session_id = $2
`

type MoveFavoritesToUserParams struct {
	UserID    sql.NullInt64
	SessionID sql.NullString
}

func (q *Queries) MoveFavoritesToUser(ctx context.Context, arg MoveFavoritesToUserParams) error {
	_, err := q.db.ExecContext(ctx, moveFavoritesToUser, arg.UserID, arg.SessionID)
	return err
}

const removeFavorite = `-- name: RemoveFavorite :exec
DELETE FROM favorites
WHERE book_id = $1
  AND (
    session_id = $2
        OR user_id = $3
    )
`

type RemoveFavoriteParams struct {
	BookID    int64
	SessionID sql.NullString
	UserID    sql.NullInt64
}

func (q *Queries) RemoveFavorite(ctx context.Context, arg RemoveFavoriteParams) error {
	_, err := q.db.ExecContext(ctx, removeFavorite, arg.BookID, arg.SessionID, arg.UserID)
	return err
}
