// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
)

type Book struct {
	ID     int32
	Title  string
	Author string
	Price  string
}

type Favorite struct {
	ID        int32
	SessionID sql.NullString
	UserID    sql.NullInt64
	BookID    int64
	CreatedAt sql.NullTime
}
